# Generated by Django 4.2.4 on 2023-11-15 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Парковка возле главного здания', verbose_name='Название')),
                ('address', models.TextField(default='2-я Бауманская ул., 5, стр. 4, Москва', verbose_name='Адресс')),
                ('places_count', models.IntegerField(default=50, verbose_name='Количество мест')),
                ('cost', models.IntegerField(default=2000, verbose_name='Стоимость (в час)')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=2, verbose_name='Время (часов)')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 11, 15, 8, 33, 22, 776038, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 11, 15, 8, 33, 22, 776038, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 11, 15, 8, 33, 22, 776038, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('parkings', models.ManyToManyField(null=True, to='parking.parking', verbose_name='Парковки')),
            ],
            options={
                'verbose_name': 'Рассчет',
                'verbose_name_plural': 'Рассчеты',
            },
        ),
    ]
