# Generated by Django 4.2.4 on 2023-11-15 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name': 'Парковка', 'verbose_name_plural': 'Парковки'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.RemoveField(
            model_name='parking',
            name='cost',
        ),
        migrations.AlterField(
            model_name='parking',
            name='image',
            field=models.ImageField(upload_to='parkings', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 8, 43, 41, 453787, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 8, 43, 41, 453787, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 8, 43, 41, 453787, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
