# Generated by Django 4.2.4 on 2023-11-18 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parking_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='value',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 7, 39, 37, 149852, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 7, 39, 37, 149614, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 7, 39, 37, 149848, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
