# Generated by Django 4.2.5 on 2024-01-05 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='image',
            field=models.ImageField(blank=True, default='parkings/default.png', null=True, upload_to='parkings', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 5, 14, 55, 59, 696427, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
    ]
