# Generated by Django 4.2.7 on 2023-12-16 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 16, 10, 26, 51, 236721, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, verbose_name='Статус'),
        ),
    ]
