# Generated by Django 4.2.8 on 2023-12-19 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ticket_date_created_alter_ticket_moderator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price_status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_entry',
            field=models.CharField(blank=True, default=0, verbose_name='Время въезда'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_entry_status',
            field=models.IntegerField(default=1, verbose_name='Статус времени въезда'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 19, 16, 23, 24, 2063, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
    ]
